### ISSUE TITLE
command line tool to output rust code [HELP WANTED]

### ISSUE THREAD

**Issue by ahl** [oxidecomputer/typify#175]
It would be great to have a command line tool in the crate that we could run to output a rust file from JSON schema input. Ideally `cargo run` within the repo would invoke this by default (i.e. w/o `--bin whatever`).

Perhaps it would be nice to call it `cargo-typify` and let users `cargo install cargo-typify` to run from outside of the repo.

**Comment by coreyja** [comment]
I'm thinking of picking this up!

I'm working on a related library to this and `progenitor` where instead of generating a full async client we just do the structs

So its basically a OpenAPI aware wrapper of this crate (with a few borrowed bits from 'progenitor')

All that to say I think building a CLI for this would be a good way to learn some of the guts of this crate

**Comment by ahl** [comment]
That would be awesome and I would be happy to point you in the right direction or coach you along the way.
