### ISSUE TITLE
switch `ToString` impls to `std::fmt::Display`

### ISSUE THREAD

**Issue by ahl** [oxidecomputer/typify#198]

**Comment by Flowneee** [comment]
Hi. Is there any progress with this issue? I am recently experienced some inconvenience with having ToString instead of Display - in tracing `#[instrument]` macro it require either to convert argument with `to_string()` or provide some wrapper with Display implementation. 

If there is no work being done on this issue right now and you don't mind I can try to implement it and send a PR.

**Comment by ahl** [comment]
No work ongoing. A PR would be very welcome!

**Comment by louisdewar** [comment]
I've made a PR that I think addresses this in #663

**Comment by ahl** [comment]
Closed by #663
