### ISSUE TITLE
Error parse json schema generated by atdgen/atdcat

### ISSUE THREAD

**Issue by gborough** [oxidecomputer/typify#450]
Trying to parse a schema file which is generated by atdgen/atdcat tool

Schema file source(confirmed valid): 
https://github.com/semgrep/semgrep-interfaces/blob/cd26a041f59b5321ba1088418b2e2d304c24f196/semgrep_output_v1.jsonschema

Cli error produced:

<code>The application panicked (crashed).
Message:  not yet implemented
Location: /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/typify-impl-0.0.14/src/convert.rs:43</code>

**Comment by ahl** [comment]
It looks like this succeeds in the main branch.... however it turns out to be generating the wrong code. Looking more closely, version 0.0.14 fails on structures such as this one:

```json
    "rule_id_and_engine_kind": {
      "type": "array",
      "minItems": 2,
      "items": false,
      "prefixItems": [
        { "$ref": "#/definitions/rule_id" },
        { "$ref": "#/definitions/engine_kind" }
      ]
    },
```

This makes use of the `prefixItems` construct ... which is unsupported by typify. I had not seen this before, apparently this is a new construction in 2020-12 that creates an alternative way of doing what was already possible in 2019-09 via a different mechanism:

> In Draft 4 - 2019-09, tuple validation was handled by an alternate form of the items keyword. When items was an array of schemas instead of a single schema, it behaved the way prefixItems behaves.

https://json-schema.org/understanding-json-schema/reference/array

Also: https://json-schema.org/draft/2020-12/release-notes#changes-to-items-and-additionalitems Perhaps its a significant enough improvement to warrant the change.

---

For the time being you could process the JSON to convert these structures:

```json
    "rule_id_and_engine_kind": {
      "type": "array",
      "minItems": 2,
      "additionalItems": false,
      "items": [
        { "$ref": "#/definitions/rule_id" },
        { "$ref": "#/definitions/engine_kind" }
      ]
    },
```

In the fullness of time I'd like typify to support additional JSON schema variants.

**Comment by gborough** [comment]
Thanks the main branch is confirmed working. Would be awesome to support additional schema variants, but for now it does the job well

**Comment by ahl** [comment]
Is that working for you? As I said: we don't yet use the prefixItems so the generated code will be inaccurate for some types.

**Comment by gborough** [comment]
> Is that working for you? As I said: we don't yet use the prefixItems so the generated code will be inaccurate for some types.

Yes I've done e2e test and working fine, thanks again
